package chencj.cc.oa.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Role.java
//  @ Date : 2018/11/5
//  @ Author : 
//
//




public class Role implements Serializable{
    private String role_name;
    private Long role_id;
    private String role_description;
    private Set<User> users = new HashSet<>();
    private Set<Privilege> privileges = new HashSet<>();
    
    
	public Set<Privilege> getPrivileges() {
		return privileges;
	}
	public void setPrivileges(Set<Privilege> privileges) {
		this.privileges = privileges;
	}
	public String getRole_name() {
		return role_name;
	}
	public void setRole_name(String role_name) {
		this.role_name = role_name;
	}
	public Long getRole_id() {
		return role_id;
	}
	public void setRole_id(Long role_id) {
		this.role_id = role_id;
	}

	public Set<User> getUsers() {
		return users;
	}
	public void setUsers(Set<User> users) {
		this.users = users;
	}
	@Override
	public String toString() {
		return "Role [role_name=" + role_name + ", role_id=" + role_id
				+ ", description=" + role_description + "]";
	}
	public String getRole_description() {
		return role_description;
	}
	public void setRole_description(String role_description) {
		this.role_description = role_description;
	}
    
}
