package chencj.cc.oa.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : User.java
//  @ Date : 2018/11/5
//  @ Author : 
//
//




public class User implements Serializable{
    private String user_name;
    private Long user_id;
    private String password;
    private String telephone;
    private String email;
    private String login_name;
    private Department department ;
    private Set<Role> roles = new HashSet<>();
	private String sex;
	private String description;
	
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public Long getUser_id() {
		return user_id;
	}
	public void setUser_id(Long user_id) {
		this.user_id = user_id;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getTelephone() {
		return telephone;
	}
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getLogin_name() {
		return login_name;
	}
	public void setLogin_name(String login_name) {
		this.login_name = login_name;
	}
	public Department getDepartment() {
		return department;
	}
	public void setDepartment(Department department) {
		this.department = department;
	}
	public Set<Role> getRoles() {
		return roles;
	}
	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}
	
	public boolean hasPermission(String priName){
		if(login_name.equals("admin"))return true;
		for (Role role : roles) {
			for (Privilege privilege : role.getPrivileges()) {
				if (privilege.getPriName().equals(priName)) {
					return true;
				}
			}
		}
		return false;
	}
	@Override
	public String toString() {
		return "User [user_name=" + user_name + ", user_id=" + user_id
				+ ", telephone=" + telephone + "]";
	}
    
}
